### ISSUE TITLE
Roadmap 2022 

### ISSUE THREAD

**Issue by wewoor** [DTStack/dt-sql-parser#52]
## 三季度

- [ ] 完善 FlinkSQL, 补充单元测试
- [ ] 完善 SparkSQL, 补充单元测试
- [ ] Bug 修复
- [ ] 查看支持 Autocomplete 的方案

## 四季度
- [ ] 支持 Autocomplete 
- [ ] 集成到 [monaco sql language](https://github.com/DTStack/monaco-sql-languages)
- [ ] 升级到产品
